env:
  browser: true
  es6: true

extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:jest/recommended'
  - 'plugin:prettier/recommended'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module

plugins:
  - react
  - jest
  - prettier

settings:
  react:
    version: detect

rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
